[package]
name = "solana-marketplace"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"

[dependencies]
solana-program = "1.18.26"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1